version: '3.8'
services:
    nginx:
        container_name: nginx_${APPLICATION_NAME}
        image: nginx
        volumes:
            - ./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/home/wwwroot/movies
        ports:
            - ${APPLICATION_PORT}:8080
        restart: on-failure
        depends_on:
            - php

    php:
        container_name: php_${APPLICATION_NAME}
        build: .docker
        restart: on-failure
        volumes:
            - ./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/home/wwwroot/movies
        user: 1000:1000

    composer:
        container_name: composer_${APPLICATION_NAME}
        image: composer/composer
        volumes:
            - .:/app
        command: install

    postgres:
        image: postgres:13-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports: [5432]

    postgres_test:
        image: postgres:13-alpine
        restart: on-failure
        env_file:
            - .env.test
        environment:
            POSTGRES_DB: ${DB_NAME_TEST}
            POSTGRES_USER: ${DB_USER_TEST}
            POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
        ports: [5432]
